name: JumpAndRun
version: 1.1
main: de.smoofy.jumpandrun.main.JAR
api-version: '1.20'
authors: [ Smoofy ]
description: A simple JumpAndRun Plugin.
website: http://dc.smoofy19.de/
commands:
  jumpandrun:
    aliases:
      - jar